### ISSUE TITLE
[Cursor Extension] Can't install with latest updates

### ISSUE THREAD

**Issue by Rayk0** [alexpasmantier/television-vscode#3]
**Description**
Can't install Cursor extension because it is not compatible with the current version.

**How to reproduce ?**
Install Cursor and try to install the extension.

**Environment**
 - OS: macOS Sequoia 15.3 M1 Max
 - Rust version: [e.g. 1.50.0]
 - Project version: v.0.10.6
 - Cursor / VS Code version : 0.45.11 / 1.96.2

<img width="351" alt="Image" src="https://github.com/user-attachments/assets/2b375bc3-8447-41c1-bca5-d35c5b9ec823" />

EDIT: The extension works fine with the latest VS Code version. Maybe can you make it retrocompatible ?

**Comment by alexpasmantier** [comment]
Fixed in #3

**Comment by BigMitchGit** [comment]
@alexpasmantier just letting you know that the extension in vscode marketplace hasn't been updated yet, could you update that?

**Comment by alexpasmantier** [comment]
<img width="1080" alt="Image" src="https://github.com/user-attachments/assets/733f02de-bfdc-4a55-ad56-56d6dcc4c713" />

https://marketplace.visualstudio.com/items?itemName=alexpasmantier.television

I believe the application is now showing 0.1.3 on the visual studio marketplace so you should be able to get the last version.

**Comment by BigMitchGit** [comment]
Doesn't seem to include my pull requests, still can't install it on Cursor due to version engine. Did you rebuild it and push it to vscode marketplace? Not too sure how that works with vscode.

**Comment by BigMitchGit** [comment]
Oh I see.

`"engines": {
    "vscode": "^1.97.0"
  },`

this is in package.json, did you change this after my pull request? I had changed this to 1.96

**Comment by alexpasmantier** [comment]
Had some issues with the 1.96 version but can't reproduce anymore so I'll be releasing a new version with 1.96 shortly 😊
